name: Run Azure Login with OIDC
on:
 push:
 workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Retrieve VM Private IP
        id: get-vm-ip
        run: |
          private_ip=$(az vm list-ip-addresses \
            --name vm-test-actions \
            --resource-group rg-actions-test \
            --query "[].virtualMachine.network.privateIpAddresses[0]" \
            --output tsv)
          echo "PRIVATE_IP=$private_ip" >> $GITHUB_ENV

      - name: Display VM Private IP
        run: echo "The VM private IP address is $PRIVATE_IP"

     
      # - name: Copy artifacts to azure VM 
      #   uses: appleboy/scp-action@master
      #   with:
      #      host: 'vm-test-01' 
      #      username: 'vmadmin'
      #      password: ${{ secrets.vmpassword }} 
      #      source:  .
      #      target: 'C:\\Users\\vmadmin'
