name: Run Azure Login with OIDC
on:
 push:
 workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Find VM Private IP address
        id: get_vm_private_ip
        run: |
          vm_private_ip=$(az vm show -g rg-actions-test -n vm-test-actions --query privateIps[0] -o tsv)
          echo "::set-output name=vm_private_ip::${vm_private_ip}"
     
      # - name: Copy artifacts to azure VM 
      #   uses: appleboy/scp-action@master
      #   with:
      #      host: 'vm-test-01' 
      #      username: 'vmadmin'
      #      password: ${{ secrets.vmpassword }} 
      #      source:  .
      #      target: 'C:\\Users\\vmadmin'
