name: Test Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: print greeting
        run: | 
          echo "Hello world!"
          echo "${{ secrets.name }}"
          echo "${{ vars.name }}"
      - name: print goodbye
        run: echo "bye!"
